// <auto-generated />
using System.Collections.Generic;
using EF10.JsonTypeSupportForSqlServer2025;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF10.JsonTypeSupportForSqlServer2025.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    partial class BlogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF10.JsonTypeSupportForSqlServer2025.Entities.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("json");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Details", "EF10.JsonTypeSupportForSqlServer2025.Entities.Blog.Details#BlogDetails", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Description");

                            b1.Property<int>("Viewers");

                            b1.ToJson("Details");
                        });

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
