// <auto-generated />
using EF11.SqlServerVectorIndexes;
using Microsoft.Data.SqlTypes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF11.SqlServerVectorIndexes.Migrations;

[DbContext(typeof(MyDbContext))]
[Migration("20260827131540_InitialMigration")]
partial class _20260827131540_InitialMigration
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-preview.7.26381.103")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("EF11.SqlServerVectorIndexes.Entities.Blog", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<SqlVector<float>>("Embedding")
                    .HasColumnType("vector(3)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("Embedding")
                    .HasAnnotation("SqlServer:VectorIndexMetric", "cosine");

                b.ToTable("Blogs");
            });
#pragma warning restore 612, 618
    }
}
